GET http://localhost:9999/api/v1/label
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI5NTg0NzIsInVzZXJJZCI6MTAwfQ.N6Wtm5nVbE8vPgg3mtW4F-HvWz2W3rxR_ozwwPdwRL8

###
GET http://localhost:9999/api/v1/label/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI4MTU0MTQsInVzZXJJZCI6MTAwfQ.HdUYLlj2RMvSqSnv5lazeoSAQXoj32c9wCn6Qjgos54

###
POST http://localhost:9999/api/v1/label
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI4OTgxNDQsInVzZXJJZCI6MTAwfQ.fckYRyHDdGFYxyb6o1N5gu8ts9PiwI4XDsf1aDcwjkQ

{
  "name": "Hobby",
  "date": "2019-01-01T00:00:00Z"
}


###
PUT http://localhost:9999/api/v1/label/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI4MTU0MTQsInVzZXJJZCI6MTAwfQ.HdUYLlj2RMvSqSnv5lazeoSAQXoj32c9wCn6Qjgos54

{
  "name": "Etiqueta actualizada",
  "date": "2019-01-01T00:00:00Z"
}

###
DELETE http://localhost:9999/api/v1/label/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3d3cudWNiLmVkdS5ibyIsIm5hbWUiOiJKdWFuIFBlcmV6IiwidHlwZSI6IkFVVEgiLCJleHAiOjE2ODI5NTg0NzIsInVzZXJJZCI6MTAwfQ.N6Wtm5nVbE8vPgg3mtW4F-HvWz2W3rxR_ozwwPdwRL8